### PR TITLE
Features/umd

### PR DESCRIPTION
**Pull request by dreef3**
Another approach for #749.

* Added UMD wrapper: https://github.com/umdjs/umd/blob/master/templates/returnExports.js
* Fixed karma dependency
* Added Angular.js as peer dependency (you'll need it anyway if you use it in Webpack/Browserify)

### CODE REVIEW

**Comment by bholloway** [comment]
+1

**Comment by cypherq** [comment]
@mgonto is there any reason why it hasn't been merged into codebase? Can I sync branch? Without this it's impossible to use `restangular` with Webpack directly (without wrapping it with UMD).

**Comment by mgonto** [comment]
Ready to merge! Can you please rebase?

**Comment by danielmorlock** [comment]
+1

**Comment by daviesgeek** [comment]
@dreef3 Can you rebase so we can merge this?

**Comment by dreef3** [comment]
@daviesgeek rebased. BTW is it required to update `dist/` contents as well?

**Comment by dreef3** [comment]
Also removed unnecessary export to global object, added comment with link to original UMD template.

**Comment by daviesgeek** [comment]
@dreef3 I'm not sure if we are requiring the `dist` folder to be updated. @ConcurrentHashMap @pedromarce ?

**Comment by fyyyyy** [comment]
+1

**Pull request merged**
