### PR TITLE
add ability to restangularize a collection with fromServer set

### PR DESCRIPTION
**Pull request by Gi7mo**

### CODE REVIEW

**Comment by daviesgeek** [comment]
Thanks so much for this PR. This looks like a good start to a great PR!

A couple of things before I merge:
- [ ] Can you please verify that there aren't any other PRs with this same change?
- [ ] Can you please add tests?
- [ ] Can you please update the docs?

**Comment by Gi7mo** [comment]
other pr with the same change #1098

**Comment by Gi7mo** [comment]
all done

**Comment by daviesgeek** [comment]
Thank you. I will review this shortly. I closed the other PR, as it isn't up to date with master, and doesn't include the documentation and unit tests.

**Comment by daviesgeek** [comment]
This looks good. I like it. Would you mind adding one more test:

```js
    it("should have fromServer set when restangularizeElement is called with that param", function() {
      var element = Restangular.restangularizeElement(null, {}, 'accounts', true);
      expect(element.fromServer).toEqual(true);

      element = Restangular.restangularizeElement(null, {}, 'accounts', false);
      expect(element.fromServer).toEqual(false);

      element = Restangular.restangularizeElement(null, {}, 'accounts');
      expect(element.fromServer).toEqual(false);
    });
```

**Pull request merged**
