### PR TITLE
Create support for Matrix URIs

### PR DESCRIPTION
**Pull request by HenriqueLimas**
PR related to issue #968. @grabbou

### CODE REVIEW

**Comment by gkohen** [comment]
@mgonto this is something that we want to use to support complex filtering in our REST APIs. Want can we do to speed up the merge? 
Thanks again for this awesome piece of software. It's a lifesaver.

**Comment by bernyfox** [comment]
+1

**Comment by BBeauchemin** [comment]
+1

**Comment by HenriqueLimas** [comment]
I think we can close this one, the structure of the code changed, so it needs to be done again.

**Pull request closed without merging**
