### PR TITLE
added custom collection method to scoped service

### PR DESCRIPTION
**Pull request by FabienDehopre**
add custom restangular collection methods to object returned by service() #719

### CODE REVIEW

**Comment by sdbondi** [comment]
Will this ever get merged?

**Comment by grabbou** [comment]
Yes, but we are waiting for some additional unit tests from @FabienDehopre. If he is not going to provide them, we will be merging those changes pretty soon (we have plenty of PR's awaiting merge and we recently decided to do the final catch up on them).

**Comment by sdbondi** [comment]
@grabbou Thanks, wish I had time to help :) Will let you know here if I do, because I am using (more or less) this piece of code in an app and I'd prefer to use an "official" version rather than my fork. @FabienDehopre Are you up for writing these tests?

**Comment by grabbou** [comment]
:) Not sure about that as repo seems to be deleted. If you are using them, maybe you can paste some code snippets so I can wrap them in more proper unit tests @sdbondi ?

**Comment by sdbondi** [comment]
My code is here: https://github.com/fixate/restangular/blob/angelscup/src/restangular.js#L1258
Really quick and dirty so I can carry on with things.
Taken from this PR - i.e. https://github.com/mgonto/restangular/pull/734/files

**Comment by grabbou** [comment]
Yeah, that's okey. Just wanted to ask if you can provide some plunkr or whatever with basic usage?

**Comment by sdbondi** [comment]
Right, I think I'd rather just write the tests when I get time :) `Restangular.service('cats').customGET(...)`

**Comment by grabbou** [comment]
You're welcome, I promise to merge it as soon as it passes all the tests. Feel free to add readme part as well explaining usage.

**Comment by sdbondi** [comment]
Thanks - I probably wouldn't add as many functions to the list as in this PR - just the custom ones - but if there is a use case I expect separate PRs for extra service functions will come.

**Comment by FabienDehopre** [comment]
Please check #735 instead. 
The code is better and there is a test.

**Comment by sdbondi** [comment]
Ok so this has already been done (Cleanest PR here? https://github.com/mgonto/restangular/pull/809) - set for v1.5.0. It's been a while since there has been a release - hope we can get some of these PRs soon. Thanks @FabienDehopre

**Comment by grabbou** [comment]
We are having a Hangouts call with @mgonto today/tomorrow to review changes done to master since the last release + merging my wip/cleanup branch to hopefully release 1.5.0 this week! It ain't take too long guys, promise :)

**Comment by grabbou** [comment]
The cleanest PR is here #809 and it's been already merged so it's just a matter of new release.

**Comment by sdbondi** [comment]
Great to hear! Thanks guys :) :+1:

**Pull request closed without merging**
