### PR TITLE
Fix#696 - #696 Add configuration option to use plain() by default

### PR DESCRIPTION
**Pull request by Nihaux**
setPlainByDefault(true|false)

### CODE REVIEW

**Comment by Vlodkoo** [comment]
Anybody with "write acsess", can you merge this pull request ?

**Comment by daviesgeek** [comment]
Would you mind squashing all these commits into one before this gets merged?

**Comment by Nihaux** [comment]
@daviesgeek done, sry for the delay

**Comment by daviesgeek** [comment]
Sorry, one more picky thing. Can you please cleanup the commit messages before I merge this, then I'll get it merged in!

**Comment by vinhboy** [comment]
@Nihaux come back and make it happen dude. Thanks!

**Comment by Nihaux** [comment]
@daviesgeek done

**Comment by fnash** [comment]
Need this! When will this PR be merged? @daviesgeek

**Comment by anoopmd** [comment]
@Nihaux Thanks for this. I hope this gets into release and pushed into bower soon, Currently I am directly pointing to master so that I can use this feature in my project.

**Pull request merged**
