### PR TITLE
Promise based request interceptors

### LINKED ISSUE #891: Pre-request validation on a Restangular level.
Hi, there!

I've played with Restangular for a while now. I've come across an issue, though, that seems interesting and that could lead me to make an improvement pull-request, if anyone is interested and if @mgonto find it nice to go into Restangular's code.

So, I was dealing with pre-request validation. For us to have a case of study, let's imagine a simple password size validation:

``` js
function validPassword(password) {
  return password.length >= 8;
}
```

Now, lets say we use Restangular for the authentication in the following way:

``` js
Restangular.one('login').doPOST({password: '12345678'});
```

Ok, that's a pretty simple example. Now, the password validation part would have to rely on controller logic (besides the server side validation, of course), so that the request is only made if a valid password is attempted. IMHO, that is very bad for a large application, that could have many of it's parts using `login` Restangular route.

Well, I thought we could arrange that via `requestInterceptors`. My idea was to make `requestInterceptors` be able to return a promise, when they need to deal with something before doing the actual request. That would allow, for instance, to write these following code:

``` js
// Reject the request promise when password is not valid.
Restangular.addRequestInterceptor(function (element, op, what, url) {
  if (what === 'login' && op === 'post') {
    return validPassword(element.password) ? element : $q.reject('Invalid password');
  }
  return element;
});
```

That would allow, among other things, for chained dependent requests and any asynchronous code validation, like the the following:

``` js
Restangular.addRequestInterceptor(function (element, op, what, url) {
  if (what === 'login' && op === 'post') {
    return $timeout(function () {
      return validPassword(element.password);
    }, 5000);
  }
  return element;
});
```

So, what do you guys think?

### PR DESCRIPTION
**Pull request by lucasconstantino**
This pull-request closes #891, which is an issue created by myself. It intends to make fullRequestInterceptors be able to make asynchronous transformations before the actual request happens.

Because it is a promise based approach, it also makes it possible for a interceptor to reject the user request before any data travels. This is specially useful on situations where you want to validate requests in the client side before even bothering requesting the server. That could, of course, be implemented on a *controller* level of an application, but that makes things like per-route validation much more centralized and organized.

I've run all tests and everything seems to continue working after this major change. Besides, I'm already using the code on a project in production. Anyway, I hope more people can give it a try before we make it to the master. An alternative to introduce such a change is to actually implement this idea only when [Restangular gets build from ground up to 2.0](http://github.com/mgonto/restangular/issues/890), which I hope to help make it happen soon.

*P.s.: If I find some time I'll write tests for this pull-request.*

### CODE REVIEW

**Comment by tmuldoon-aimia** [comment]
Exactly the same use case as @Schunk. Is this coming anytime soon?

**Comment by javierquevedo** [comment]
Pretty similar use case over here. Please consider evaluating this merge request which is about 1.5 years old now :+1:

**Comment by daviesgeek** [comment]
@lucasconstantino Can you rebase and then I'll take a look at this?

**Comment by gauravarora** [comment]
I have exactly similar use case. I would like to refresh my access token and only then let the request through. Right now, I have no choice but to make the API call while still refreshing the access token in the background and then re-request when the API call errors out.

**Comment by lukeggchapman** [comment]
@daviesgeek I've rebased this and created a new PR #1433 

@lucasconstantino The main changes I made was to change[ `urlHandler.resource.apply(window, ...`](https://github.com/mgonto/restangular/pull/1433/files#diff-a8a4d5ae8c575e260ea5221aef9a662fR1174) and [`config.fullRequestInterceptor.apply(window, ...`](https://github.com/mgonto/restangular/pull/1433/files#diff-a8a4d5ae8c575e260ea5221aef9a662fR1186) to be applied with the context of itself rather than window.

All tests are passing and I should be using this over the next 2 days and hopefully not find any bugs.

**Comment by lucasconstantino** [comment]
Thansk, @lukeggchapman! I don't really use Restangular anymore, so I wouldn't make this rebase so soon. I guess we can close this one.

**Comment by gauravarora** [comment]
@lucasconstantino if I may ask, what do you use instead?

**Comment by lucasconstantino** [comment]
@gauravarora I don't have any projects in angular, beside some old ones. React took my heart :)

By the way: even in React environment I still miss a lot of the Restangular functionalities... once I though about extracting Restangular core from Angular. I think @mgonto also thought about this a while ago.

**Comment by daviesgeek** [comment]
Sorry all :/ It's been really hard keeping up with this project, since I'm really the only active one going through PRs and issues.

@gauravarora Take a look at https://github.com/daviesgeek/restjs I basically re-wrote Restangular in vanilla JS with a few changes. It's still a 1.0 for sure, but I can assure you, I *will* be maintaining it!

**Pull request closed without merging**
