### PR TITLE
Change _.contains to _.includes for compatability with lodash 4 #1314

### PR DESCRIPTION
**Pull request by billjohnston**
Also added local grunt and updated karma to get tests to work

### CODE REVIEW

**Comment by soyuka** [comment]
:+1:

**Comment by mandax** [comment]
:+1:

**Comment by fedxgibson** [comment]
Its good! Please merge it

**Comment by ConcurrentHashMap** [comment]
@billjohnston Good job! :+1: I tested it locally and it works like a charm. I contacted @mgonto yesterday and offered him some help in maintaining this repository. He was very thankful for that, as he told me that he unfortunately hasn't the time to actively maintain it and added me as a collaborator.

I will merge this PR as soon I've read on some of the other issue just to be sure that merging this and bumping the version won't break anything.

**Comment by pascaloliv** [comment]
Hey ! Looks good - you can merge :+1:

**Comment by the-james-burton** [comment]
I've tested it too - works nicely for me, thanks!

**Comment by ConcurrentHashMap** [comment]
@billjohnston and all the others in this thread: Thanks!

**Comment by soyuka** [comment]
Yeah! Thanks @ConcurrentHashMap! If you need help to review some other PR please ping me in the topic!

**Comment by billjohnston** [comment]
Nice! thanks for merging @ConcurrentHashMap, glad we could get this fixed.

**Pull request merged**
