### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by melnikaite**
#1023

### CODE REVIEW

**Comment by MattKetmo** [comment]
+1

**Comment by billxinli** [comment]
+1

**Comment by melnikaite** [comment]
it's not a problem because in this PR `"lodash": ">=1.3.0"`
the real problem is apathy of restangular developers

**Comment by grabbou** [comment]
Deps to be updated tomorrow. Stay tuned.

**Comment by grabbou** [comment]
Dependencies updated in a separate branch. Waiting for @mgonto to release a new version after he goes back from conferences. For the time being - you can refer to this branch. Further updates will be provided in the issue connected with this PR. Thanks for your support.

**Pull request closed without merging**
