### PR TITLE
adds more realistic POST response for accounts, with id

### PR DESCRIPTION
**Pull request by jessbowers**
POST'ing an account now returns a new account object with the "id" filled in, rather than the client sending it in the POST.

### CODE REVIEW

**Comment by grabbou** [comment]
Nice one :) Thanks.

**Comment by daviesgeek** [comment]
This looks good @jessbowers . Will probably merge in shortly

**Comment by jessbowers** [comment]
@daviesgeek want me to rebase to bring it up to date?

**Comment by jessbowers** [comment]
rebased

**Comment by daviesgeek** [comment]
Sure, thanks. I'll review it and merge when i have some time to read it more thoroughly

**Pull request merged**
