### PR TITLE
Custom patch

### PR DESCRIPTION
**Pull request by ridiculous**
Addresses #1076

### CODE REVIEW

**Comment by nb88a** [comment]
:+1:

**Comment by burnhambp** [comment]
+1 to get this merged.

**Comment by default0** [comment]
+1

**Comment by cagodoy** [comment]
@mgonto merge this PR please

**Comment by dallincrane** [comment]
@mgonto Please merge!

**Comment by ridiculous** [comment]
Is @mgonto alive?

**Comment by hyungouk** [comment]
@mgonto  I need this too! please merge!

**Comment by daviesgeek** [comment]
@ConcurrentHashMap @pedromarce any reason why we can't merge this in?

**Comment by ConcurrentHashMap** [comment]
@daviesgeek It's an API change, but it only adds a useful (and before missing) function. So I don't see how this API change could break anything. Go merge it!

**Comment by lapinvert** [comment]
These changes aren't updated in the dist/ folder !

**Comment by daviesgeek** [comment]
@lapinvert This should be in the next release, thus, it's not up to date yet…

**Comment by iberodev** [comment]
any update on this?
I am using the latest restangular available at Bower `"restangular": "1.5.2",` and I am getting `this.consignmentsRestangular.customPATCH is not a function`

**Comment by nazar** [comment]
please merge 🙏

**Comment by iberodev** [comment]
it says it's merged but I keep getting `.customPATCH is not a function` with version `"restangular": "1.5.2"`

**Comment by daviesgeek** [comment]
@iberodev It has been merged but 1.5.3 hasn't been released yet. Use the GitHub hash for this specific commit and it'll work!

**Pull request merged**
