### PR TITLE
Honor authority without schema in url

### PR DESCRIPTION
**Pull request by ar45**
Also fixed wrong positional arguments swapped 'angular' and 'lodash'.
Updated dependency requires lodash >=1.3.1

### CODE REVIEW

**Comment by daviesgeek** [comment]
Thanks so much for your contribution. This looks like a good PR!

I'm not sure the intent of [the third commit](https://github.com/mgonto/restangular/pull/1374/commits/b73bdb5c4c45f37f38d323e6ad7ad6b3eb9b72a2). Could you explain it a little more in depth of what exactly is happening?

Also the second commit is unnecessary. I am inclined to stick with the current version specified by Restangular, as you can easily upgrade Lodash to 1.3.1 within your specific project.

**Comment by ar45** [comment]
[Here](https://github.com/mgonto/restangular/pull/1374/commits/b73bdb5c4c45f37f38d323e6ad7ad6b3eb9b72a2/#diff-a8a4d5ae8c575e260ea5221aef9a662fR11) The factory function is called and passed the parameters `(_, angular)` which is currently in wrong order as it is exported as `(angular, _)`.
The third commit fixes that.

In regards to the dependency on lodash >= 1.3.1, I had some errors when I tried using lodash 1.3.0. However, since I cannot reproduce that now. I will remove that commit.

**Comment by ar45** [comment]
@daviesgeek I removed the second commit.

**Comment by daviesgeek** [comment]
[The link](https://github.com/mgonto/restangular/pull/1374/commits/b73bdb5c4c45f37f38d323e6ad7ad6b3eb9b72a2/#diff-a8a4d5ae8c575e260ea5221aef9a662fR11) you supplied is now broken; would you mind updating that, then I can take a look at what you're talking about?

**Comment by ar45** [comment]
@daviesgeek  https://github.com/mgonto/restangular/pull/1374/files#diff-a8a4d5ae8c575e260ea5221aef9a662fR11

**Comment by daviesgeek** [comment]
Ah perfect. I see the issue now. Let me just do one more read through, and I'll merge

**Comment by ar45** [comment]
@daviesgeek Thanks

**Comment by daviesgeek** [comment]
Thank *you*!

**Pull request merged**
